apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-serviceone
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: one
  template:
    metadata:
      name: service-one
      labels:
        service: one
    spec:
      containers:
      - name: deploy-one
        image: veerendrakumar/serviceone:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: google-one-service
spec:
  selector:
    service: one
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
